spring:
  application:
    name: realtimechat
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost:3310}/chatRoom?serverTimezone=Asia/Seoul
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root_password}
  jpa:
    hibernate:
      ddl-auto: create # 기존 'create'를 변경했으나 필요에 따라 수정
    show-sql: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  kafka:
    bootstrap-servers: ${ KAFKA_BOOTSTRAP_SERVERS:localhost:9092 }
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID:my-group}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

jwt:
  secret-key: 4Ixa3PT4KhLW1fz4bJoY8z2dR4Gk7jHpB3Yw8mQvL9NdXx5vT9Yw8VhN3rB4YxK2
